spring:
  application:
    name: urlshortener
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/urlshortener
    username: app
    password: secret
  data:
    redis:
      host: localhost
      port: 6379